require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'backpacker' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'backpackerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
Multiple commands produce '/Users/TRECE/Library/Developer/Xcode/DerivedData/backpacker-dvmmnvsgzuhlefcfbyofbhpdosge/Build/Products/Debug-iphonesimulator/backpacker.app/FontAwesome.ttf':
1) Target 'backpacker' (project 'backpacker') has copy command from '/Users/TRECE/SideProject/backpacker/Frontend/node_modules/react-native-vector-icons/Fonts/FontAwesome.ttf' to '/Users/TRECE/Library/Developer/Xcode/DerivedData/backpacker-dvmmnvsgzuhlefcfbyofbhpdosge/Build/Products/Debug-iphonesimulator/backpacker.app/FontAwesome.ttf'
2) That command depends on command in Target 'backpacker' (project 'backpacker'): script phase “[CP] Copy Pods Resources”
