import images from './images';

const myBookings = [
    {
        id: 1,
        type: 'pending',
        pax: 3,
        store: 'Sulsul',
        time: '2020.06.20 13:00',
    },
    {
        id: 2,
        type: 'confirmed',
        pax: 4,
        store: 'Hong',
        time: '2020.06.14 14:00',
    },
    {
        id: 3,
        type: 'rejected',
        pax: 5,
        store: 'On dul',
        time: '2020.05.15 14:00',
    },
    {
        id: 4,
        type: 'confirmed',
        pax: 2,
        store: 'Hong',
        time: '2020.05.15 15:00',
    },
];

const messages = [
    {
        id: 1,
        type: 'booking',
    },
    {
        id: 2,
        type: 'deal',
    },
    {
        id: 3,
        type: 'booking',
    },
    {
        id: 4,
        type: 'booking,',
    },
];

const stores = [
    {
        id: 1,
        name: 'Guiga Korean BBQ Restaurant',
        tags: ['Korean', 'Asian', 'BBQ', 'Restaurant', 'Tanjong Pagar'],
        address: '134 Tg Pagar Rd, Singapore 0885389',
        operatingHours: {
            lunch: '10:00~2:00',
            dinner: '5:00~12:00',
        },
        coordinate: {
            latitude: 1.27747,
            longitude: 103.8434,
        },
        image: [images.spagetti, images.laksa, images.satay],

        distance: 100,
        status: 'Closed',
        menuCategories: [
            'BBQ',
            'SIDE',
            'ALCOHOLIC DRINKS',
            'NON-ALCOHOLIC DRINKS',
        ],
        menu: [
            {
                id: 1,
                name: 'Kimchi Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.laksa,
                category: 'Main',
            },
            {
                id: 2,
                name: 'Sundubu Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.nasiLemak,
                category: 'SIDE',
            },
            {
                id: 3,
                name: 'Wu-Ge-Ji Galbitang',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.satay,
                category: 'ALCOHOLIC DRINKS',
            },
            {
                id: 4,
                name: 'Hot Stone Bibimbab',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.spagetti,
                category: 'NON-ALCOHOLIC DRINKS',
            },
        ],
        deals: [
            {
                id: 1,
                type: 'coupon',
                title: 'After $20 OFF',
                store: 'Guiga Korean BBQ Restaurant',
                period: '2020.06.02 ~ 2020.06.05',
            },
        ],
    },
    {
        id: 2,
        name: 'Hong JjaJang',
        tags: ['Korean', 'Asian', 'Restaurant', 'Tanjong Pagar'],
        address: '134 Tg Pagar Rd, Singapore 0885389',
        operatingHours: {
            lunch: '10:00~2:00',
            dinner: '5:00~12:00',
        },
        // postalCode: 088514,
        coordinate: {
            latitude: 1.27752,
            longitude: 103.84377,
        },
        image: [images.spagetti, images.laksa, images.satay],
        distance: 100,
        status: 'Open',
        menuCategories: [
            'Main',
            'SIDE',
            'ALCOHOLIC DRINKS',
            'NON-ALCOHOLIC DRINKS',
        ],
        menu: [
            {
                id: 1,
                name: 'Kimchi Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.laksa,
                category: 'Main',
            },
            {
                id: 2,
                name: 'Sundubu Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.nasiLemak,
                category: 'SIDE',
            },
            {
                id: 3,
                name: 'Wu-Ge-Ji Galbitang',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.satay,
                category: 'ALCOHOLIC DRINKS',
            },
            {
                id: 4,
                name: 'Hot Stone Bibimbab',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.spagetti,
                category: 'NON-ALCOHOLIC DRINKS',
            },
        ],
    },
    {
        id: 3,
        name: 'On Dol',
        tags: ['Korean', 'Asian', 'BBQ', 'Restaurant', 'Telok Ayer'],
        address: '134 Tg Pagar Rd, Singapore 0885389',
        operatingHours: {
            lunch: '10:00~2:00',
            dinner: '5:00~12:00',
        },
        coordinate: {
            latitude: 1.27744,
            longitude: 103.84376,
        },
        image: [images.spagetti, images.laksa, images.satay],
        distance: 100,
        status: 'open',
        menuCategories: [
            'Main',
            'SIDE',
            'ALCOHOLIC DRINKS',
            'NON-ALCOHOLIC DRINKS',
        ],
        menu: [
            {
                id: 1,
                name: 'Kimchi Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.laksa,
                category: 'Main',
            },
            {
                id: 2,
                name: 'Sundubu Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.nasiLemak,
                category: 'SIDE',
            },
            {
                id: 3,
                name: 'Wu-Ge-Ji Galbitang',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.satay,
                category: 'ALCOHOLIC DRINKS',
            },
            {
                id: 4,
                name: 'Hot Stone Bibimbab',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.spagetti,
                category: 'NON-ALCOHOLIC DRINKS',
            },
        ],
    },
    {
        id: 4,
        name: 'Cho-won Garden',
        tags: ['Korean', 'Asian', 'BBQ', 'Restaurant', 'Telok Ayer'],
        address: '134 Tg Pagar Rd, Singapore 0885389',
        operatingHours: {
            lunch: '10:00~2:00',
            dinner: '5:00~12:00',
        },
        coordinate: {
            latitude: 1.27886,
            longitude: 103.84494,
        },
        image: [images.spagetti, images.laksa, images.satay],
        distance: 100,
        status: 'open',
        menuCategories: [
            'Main',
            'SIDE',
            'ALCOHOLIC DRINKS',
            'NON-ALCOHOLIC DRINKS',
        ],
        menu: [
            {
                id: 1,
                name: 'Kimchi Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.laksa,
                category: 'Main',
            },
            {
                id: 2,
                name: 'Sundubu Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.nasiLemak,
                category: 'SIDE',
            },
            {
                id: 3,
                name: 'Wu-Ge-Ji Galbitang',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.satay,
                category: 'ALCOHOLIC DRINKS',
            },
            {
                id: 4,
                name: 'Hot Stone Bibimbab',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.spagetti,
                category: 'NON-ALCOHOLIC DRINKS',
            },
        ],
    },
    {
        id: 5,
        name: 'Chicken Up Korean Restaurant',
        tags: ['Korean', 'Asian', 'Seafood', 'Restaurant', 'Tanjong Pagar'],
        address: '134 Tg Pagar Rd, Singapore 0885389',
        operatingHours: {
            lunch: '10:00~2:00',
            dinner: '5:00~12:00',
        },
        coordinate: {
            latitude: 1.27925,
            longitude: 103.84373,
        },
        image: [images.spagetti, images.laksa, images.satay],
        distance: 100,
        status: 'open',
        menuCategories: [
            'Main',
            'SIDE',
            'ALCOHOLIC DRINKS',
            'NON-ALCOHOLIC DRINKS',
        ],
        menu: [
            {
                id: 1,
                name: 'Kimchi Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.laksa,
                category: 'Main',
            },
            {
                id: 2,
                name: 'Sundubu Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.nasiLemak,
                category: 'SIDE',
            },
            {
                id: 3,
                name: 'Wu-Ge-Ji Galbitang',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.satay,
                category: 'ALCOHOLIC DRINKS',
            },
            {
                id: 4,
                name: 'Hot Stone Bibimbab',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.spagetti,
                category: 'NON-ALCOHOLIC DRINKS',
            },
        ],
    },
    {
        id: 6,
        name: 'O.BBa BBQ',
        tags: ['Korean', 'Asian', 'BBQ', 'Restaurant', 'Tanjong Pagar'],
        address: '134 Tg Pagar Rd, Singapore 0885389',
        operatingHours: {
            lunch: '10:00~2:00',
            dinner: '5:00~12:00',
        },
        coordinate: {
            latitude: 1.27827,
            longitude: 103.84396,
        },
        image: [images.spagetti, images.laksa, images.satay],
        distance: 100,
        status: 'open',
        menuCategories: [
            'Main',
            'SIDE',
            'ALCOHOLIC DRINKS',
            'NON-ALCOHOLIC DRINKS',
        ],
        menu: [
            {
                id: 1,
                name: 'Kimchi Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.laksa,
                category: 'Main',
            },
            {
                id: 2,
                name: 'Sundubu Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.nasiLemak,
                category: 'SIDE',
            },
            {
                id: 3,
                name: 'Wu-Ge-Ji Galbitang',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.satay,
                category: 'ALCOHOLIC DRINKS',
            },
            {
                id: 4,
                name: 'Hot Stone Bibimbab',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.spagetti,
                category: 'NON-ALCOHOLIC DRINKS',
            },
        ],
    },
    {
        id: 7,
        name: 'SBCD Korean Tofu House',
        tags: ['Korean', 'Asian', 'BBQ', 'Restaurant', 'City Hall'],
        address: '134 Tg Pagar Rd, Singapore 0885389',
        operatingHours: {
            lunch: '10:00~2:00',
            dinner: '5:00~12:00',
        },
        coordinate: {
            latitude: 1.27672,
            longitude: 103.84516,
        },
        image: [images.spagetti, images.laksa, images.satay],
        distance: 100,
        status: 'open',
        menuCategories: [
            'Main',
            'SIDE',
            'ALCOHOLIC DRINKS',
            'NON-ALCOHOLIC DRINKS',
        ],
        menu: [
            {
                id: 1,
                name: 'Kimchi Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.laksa,
                category: 'Main',
            },
            {
                id: 2,
                name: 'Sundubu Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.nasiLemak,
                category: 'SIDE',
            },
            {
                id: 3,
                name: 'Wu-Ge-Ji Galbitang',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.satay,
                category: 'ALCOHOLIC DRINKS',
            },
            {
                id: 4,
                name: 'Hot Stone Bibimbab',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.spagetti,
                category: 'NON-ALCOHOLIC DRINKS',
            },
        ],
    },
    {
        id: 8,
        name: 'Sindaebak BBQ',
        tags: ['Korean', 'Asian', 'BBQ', 'Restaurant', 'Telok Ayer'],
        address: '134 Tg Pagar Rd, Singapore 0885389',
        operatingHours: {
            lunch: '10:00~2:00',
            dinner: '5:00~12:00',
        },
        coordinate: {
            latitude: 1.27763,
            longitude: 103.84318,
        },
        image: [images.spagetti, images.laksa, images.satay],
        distance: 100,
        status: 'open',
        menuCategories: [
            'Main',
            'SIDE',
            'ALCOHOLIC DRINKS',
            'NON-ALCOHOLIC DRINKS',
        ],
        menu: [
            {
                id: 1,
                name: 'Kimchi Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.laksa,
                category: 'Main',
            },
            {
                id: 2,
                name: 'Sundubu Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.nasiLemak,
                category: 'SIDE',
            },
            {
                id: 3,
                name: 'Wu-Ge-Ji Galbitang',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.satay,
                category: 'ALCOHOLIC DRINKS',
            },
            {
                id: 4,
                name: 'Hot Stone Bibimbab',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.spagetti,
                category: 'NON-ALCOHOLIC DRINKS',
            },
        ],
    },
    {
        id: 9,
        name: 'Hongdae Korean Restaurant',
        tags: ['Korean', 'Asian', 'BBQ', 'Restaurant', 'Tanjong Pagar'],
        address: '134 Tg Pagar Rd, Singapore 0885389',
        operatingHours: {
            lunch: '10:00~2:00',
            dinner: '5:00~12:00',
        },
        coordinate: {
            latitude: 1.2791,
            longitude: 103.8417,
        },
        image: [images.spagetti, images.laksa, images.satay],
        distance: 100,
        status: 'open',
        menuCategories: [
            'Main',
            'SIDE',
            'ALCOHOLIC DRINKS',
            'NON-ALCOHOLIC DRINKS',
        ],
        menu: [
            {
                id: 1,
                name: 'Kimchi Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.laksa,
                category: 'Main',
            },
            {
                id: 2,
                name: 'Sundubu Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.nasiLemak,
                category: 'SIDE',
            },
            {
                id: 3,
                name: 'Wu-Ge-Ji Galbitang',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.satay,
                category: 'ALCOHOLIC DRINKS',
            },
            {
                id: 4,
                name: 'Hot Stone Bibimbab',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.spagetti,
                category: 'NON-ALCOHOLIC DRINKS',
            },
        ],
    },
    {
        id: 10,
        name: 'Supulae Korean BBQ',
        tags: ['Korean', 'Asian', 'Classic', 'Restaurant', 'Tanjong Pagar'],
        address: '134 Tg Pagar Rd, Singapore 0885389',
        operatingHours: {
            lunch: '10:00~2:00',
            dinner: '5:00~12:00',
        },
        coordinate: {
            latitude: 1.27855,
            longitude: 103.84371,
        },
        image: [images.spagetti, images.laksa, images.satay],
        distance: 100,
        status: 'open',
        menuCategories: [
            'Main',
            'SIDE',
            'ALCOHOLIC DRINKS',
            'NON-ALCOHOLIC DRINKS',
        ],
        menu: [
            {
                id: 1,
                name: 'Kimchi Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.laksa,
                category: 'Main',
            },
            {
                id: 2,
                name: 'Sundubu Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.nasiLemak,
                category: 'SIDE',
            },
            {
                id: 3,
                name: 'Wu-Ge-Ji Galbitang',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.satay,
                category: 'ALCOHOLIC DRINKS',
            },
            {
                id: 4,
                name: 'Hot Stone Bibimbab',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.spagetti,
                category: 'NON-ALCOHOLIC DRINKS',
            },
        ],
    },
];

const myDeals = [
    {
        id: 1,
        type: 'coupon',
        title: 'After $20 OFF',
        store: 'Guiga Korean BBQ Restaurant',
        period: '2020.06.02 ~ 2020.06.05',
    },
    {
        id: 2,
        type: 'store',
        title: '1+1 promotion',
        store: 'Guiga Korean BBQ Restaurant',
        period: '2020.06.02 ~ 2020.06.05',
    },
    {
        id: 3,
        type: 'coupon',
        title: '1+3 promotion',
        store: 'Guiga Korean BBQ Restaurant',
        period: '2020.06.02 ~ 2020.06.05',
    },
    {
        id: 4,
        type: 'store',
        title: '50% OFF promotio for all',
        store: 'Guiga Korean BBQ Restaurant',
        period: '2020.06.02 ~ 2020.06.05',
    },
    {
        id: 5,
        type: 'store',
        title: 'After $20 OFF',
        store: 'Guiga Korean BBQ Restaurant',
        period: '2020.06.02 ~ 2020.06.05',
    },
];

const myStores = [
    {
        id: 1,
        name: 'Guiga Korean BBQ Restaurant',
        tags: ['Korean', 'Asian', 'BBQ', 'Restaurant'],
        address: '134 Tg Pagar Rd, Singapore 0885389',
        operatingHours: {
            lunch: '10:00~2:00',
            dinner: '5:00~12:00',
        },
        image: [images.spagetti, images.laksa, images.satay],

        distance: 100,
        status: 'Closed',
        menuCategories: [
            'BBQ',
            'SIDE',
            'ALCOHOLIC DRINKS',
            'NON-ALCOHOLIC DRINKS',
        ],
        menu: [
            {
                id: 1,
                name: 'Kimchi Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.laksa,
                category: 'Main',
            },
            {
                id: 2,
                name: 'Sundubu Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.nasiLemak,
                category: 'SIDE',
            },
            {
                id: 3,
                name: 'Wu-Ge-Ji Galbitang',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.satay,
                category: 'ALCOHOLIC DRINKS',
            },
            {
                id: 4,
                name: 'Hot Stone Bibimbab',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.spagetti,
                category: 'NON-ALCOHOLIC DRINKS',
            },
        ],
    },
    {
        id: 2,
        name: 'Hong JjaJang',
        tags: ['Korean', 'Asian', 'BBQ', 'Restaurant'],
        address: '134 Tg Pagar Rd, Singapore 0885389',
        operatingHours: {
            lunch: '10:00~2:00',
            dinner: '5:00~12:00',
        },
        image: [images.spagetti, images.laksa, images.satay],
        distance: 100,
        status: 'Open',
        menuCategories: [
            'Main',
            'SIDE',
            'ALCOHOLIC DRINKS',
            'NON-ALCOHOLIC DRINKS',
        ],
        menu: [
            {
                id: 1,
                name: 'Kimchi Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.laksa,
                category: 'Main',
            },
            {
                id: 2,
                name: 'Sundubu Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.nasiLemak,
                category: 'SIDE',
            },
            {
                id: 3,
                name: 'Wu-Ge-Ji Galbitang',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.satay,
                category: 'ALCOHOLIC DRINKS',
            },
            {
                id: 4,
                name: 'Hot Stone Bibimbab',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.spagetti,
                category: 'NON-ALCOHOLIC DRINKS',
            },
        ],
    },
    {
        id: 3,
        name: 'On Dul',
        tags: ['Korean', 'Asian', 'BBQ', 'Restaurant'],
        address: '134 Tg Pagar Rd, Singapore 0885389',
        operatingHours: {
            lunch: '10:00~2:00',
            dinner: '5:00~12:00',
        },
        image: [images.spagetti, images.laksa, images.satay],
        distance: 100,
        status: 'open',
        menuCategories: [
            'Main',
            'SIDE',
            'ALCOHOLIC DRINKS',
            'NON-ALCOHOLIC DRINKS',
        ],
        menu: [
            {
                id: 1,
                name: 'Kimchi Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.laksa,
                category: 'Main',
            },
            {
                id: 2,
                name: 'Sundubu Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.nasiLemak,
                category: 'SIDE',
            },
            {
                id: 3,
                name: 'Wu-Ge-Ji Galbitang',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.satay,
                category: 'ALCOHOLIC DRINKS',
            },
            {
                id: 4,
                name: 'Hot Stone Bibimbab',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.spagetti,
                category: 'NON-ALCOHOLIC DRINKS',
            },
        ],
    },
    {
        id: 4,
        name: 'BBQ Friends',
        tags: ['Korean', 'Asian', 'BBQ', 'Restaurant'],
        address: '134 Tg Pagar Rd, Singapore 0885389',
        operatingHours: {
            lunch: '10:00~2:00',
            dinner: '5:00~12:00',
        },
        image: [images.spagetti, images.laksa, images.satay],
        distance: 100,
        status: 'open',
        menuCategories: [
            'Main',
            'SIDE',
            'ALCOHOLIC DRINKS',
            'NON-ALCOHOLIC DRINKS',
        ],
        menu: [
            {
                id: 1,
                name: 'Kimchi Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.laksa,
                category: 'Main',
            },
            {
                id: 2,
                name: 'Sundubu Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.nasiLemak,
                category: 'SIDE',
            },
            {
                id: 3,
                name: 'Wu-Ge-Ji Galbitang',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.satay,
                category: 'ALCOHOLIC DRINKS',
            },
            {
                id: 4,
                name: 'Hot Stone Bibimbab',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.spagetti,
                category: 'NON-ALCOHOLIC DRINKS',
            },
        ],
    },
    {
        id: 5,
        name: 'NUNANAA',
        tags: ['Korean', 'Asian', 'BBQ', 'Restaurant'],
        address: '134 Tg Pagar Rd, Singapore 0885389',
        operatingHours: {
            lunch: '10:00~2:00',
            dinner: '5:00~12:00',
        },
        image: [images.spagetti, images.laksa, images.satay],
        distance: 100,
        status: 'open',
        menuCategories: [
            'Main',
            'SIDE',
            'ALCOHOLIC DRINKS',
            'NON-ALCOHOLIC DRINKS',
        ],
        menu: [
            {
                id: 1,
                name: 'Kimchi Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.laksa,
                category: 'Main',
            },
            {
                id: 2,
                name: 'Sundubu Jjigae',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.nasiLemak,
                category: 'SIDE',
            },
            {
                id: 3,
                name: 'Wu-Ge-Ji Galbitang',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.satay,
                category: 'ALCOHOLIC DRINKS',
            },
            {
                id: 4,
                name: 'Hot Stone Bibimbab',
                originalPrice: 14.2,
                discountPrice: 11.2,
                image: images.spagetti,
                category: 'NON-ALCOHOLIC DRINKS',
            },
        ],
    },
];

export default {
    stores,
    myBookings,
    myDeals,
    myStores,
    messages,
};
