import {
    fetchComments,
    fetchCommentsAsync,
    fetchCommentsAsyncFailed,
    fetchMyComments,
    fetchMyCommentsAsync,
    fetchMyCommentsAsyncFailed,
    postComment,
    postCommentAsync,
    postCommentAsyncFailed,
    updateComment,
    updateCommentAsync,
    updateCommentAsyncFailed,
    deleteComment,
    deleteCommentAsync,
    deleteCommentAsyncFailed,
    resetAPIStatus,
    namespace,
    commentReducer,
} from './commentSlice';

export {
    fetchComments,
    fetchCommentsAsync,
    fetchCommentsAsyncFailed,
    fetchMyComments,
    fetchMyCommentsAsync,
    fetchMyCommentsAsyncFailed,
    postComment,
    postCommentAsync,
    postCommentAsyncFailed,
    updateComment,
    updateCommentAsync,
    updateCommentAsyncFailed,
    deleteComment,
    deleteCommentAsync,
    deleteCommentAsyncFailed,
    resetAPIStatus,
    namespace,
    commentReducer,
};
